(function() {var implementors = {
"aho_corasick":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"aho_corasick/struct.BuildError.html\" title=\"struct aho_corasick::BuildError\">BuildError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"aho_corasick/struct.MatchError.html\" title=\"struct aho_corasick::MatchError\">MatchError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"aho_corasick/struct.PatternIDError.html\" title=\"struct aho_corasick::PatternIDError\">PatternIDError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"aho_corasick/automaton/struct.StateIDError.html\" title=\"struct aho_corasick::automaton::StateIDError\">StateIDError</a>"]],
"bmp280":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"bmp280/enum.Error.html\" title=\"enum bmp280::Error\">Error</a>"]],
"gpio_cdev":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"gpio_cdev/errors/struct.Error.html\" title=\"struct gpio_cdev::errors::Error\">Error</a>"]],
"humantime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"humantime/enum.DurationError.html\" title=\"enum humantime::DurationError\">Error</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"humantime/enum.TimestampError.html\" title=\"enum humantime::TimestampError\">Error</a>"]],
"i2cdev":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"i2cdev/linux/enum.LinuxI2CError.html\" title=\"enum i2cdev::linux::LinuxI2CError\">LinuxI2CError</a>"]],
"log":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"log/struct.SetLoggerError.html\" title=\"struct log::SetLoggerError\">SetLoggerError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"log/struct.ParseLevelError.html\" title=\"struct log::ParseLevelError\">ParseLevelError</a>"]],
"nix":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"nix/env/struct.ClearEnvError.html\" title=\"struct nix::env::ClearEnvError\">ClearEnvError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"nix/errno/enum.Errno.html\" title=\"enum nix::errno::Errno\">Errno</a>"]],
"regex":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"regex/enum.Error.html\" title=\"enum regex::Error\">Error</a>"]],
"rustix":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"rustix/io/struct.Errno.html\" title=\"struct rustix::io::Errno\">Errno</a>"]],
"serial_core":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"serial_core/struct.Error.html\" title=\"struct serial_core::Error\">Error</a>"]],
"sysfs_gpio":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sysfs_gpio/enum.Error.html\" title=\"enum sysfs_gpio::Error\">Error</a>"]],
"termcolor":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"termcolor/struct.ParseColorError.html\" title=\"struct termcolor::ParseColorError\">ParseColorError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"termcolor/struct.ColorChoiceParseError.html\" title=\"struct termcolor::ColorChoiceParseError\">ColorChoiceParseError</a>"]],
"void":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.70.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"void/enum.Void.html\" title=\"enum void::Void\">Void</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()